### ISSUE TITLE
Git authentication error

### ISSUE THREAD

**Issue by barungh** [nazo6/lspinstall.nvim#1]
I am trying to install your plugin, 
but getting this error

![image](https://user-images.githubusercontent.com/12285528/130412968-11538301-844c-468b-b1af-13300e92eeea.png)

I tried both way, but it fails , even after proper authentication

![image](https://user-images.githubusercontent.com/12285528/130413608-47bc506b-9cd1-422e-a44d-dd98757f42bf.png)

***Error***

![image](https://user-images.githubusercontent.com/12285528/130413739-8295dfc1-4737-4042-9f8a-dbba470614c7.png)

*I am hoping to install Language Server properly on my Windows Machine with this plugin*

**Comment by nazo6** [comment]
Sorry, README was wrong.
Right setting is
```lua
use "nazo6/lspinstall.nvim"
```

Can you try it?

**Comment by barungh** [comment]
> Sorry, README was wrong.
> Right setting is
> 
> ```lua
> use "nazo6/lspinstall.nvim"
> ```
> 
> Can you try it?

Yes it worked ,

but language server is not installing , I am trying to install angularls
![image](https://user-images.githubusercontent.com/12285528/130450268-3722a7b5-39eb-4111-a610-f711a7f490ae.png)



![image](https://user-images.githubusercontent.com/12285528/130451119-7815f645-0765-4560-97c5-33cace724146.png)


![image](https://user-images.githubusercontent.com/12285528/130451795-ddd52742-350d-4b17-abd7-9250c1abf271.png)

**Comment by nazo6** [comment]
Fixes committed. Could you please update the plugin and try again?

I've only tested this plugin in my own environment, so there may be many other bugs...

**Comment by barungh** [comment]
> Fixes committed. Could you please update the plugin and try again?
> 
> I've only tested this plugin in my own environment, so there may be many other bugs...

![image](https://user-images.githubusercontent.com/12285528/130493293-6be84d78-c95e-48aa-aad1-749e27d57a44.png)

Updated using `:Packerupdate`  

and after that it is installing

For me, today you are the rock star of ***Github*** 

trying to successfully Install language servers on my ***Windows 10*** machine since the launch of Neovim 0.5 (lua)
( of course for my Arch Linux machine there was never any issue , but wanted to do it on my Win 10 machine )
today with your plugin it happened successfully

Thank you , 

it is really a great work

Let's make custom configuration with ***powershell*** script to install on Windows machine ( the complete neovim config ) 

☺️

**Comment by barungh** [comment]
Can you tell me why clients are not being attached ?

![image](https://user-images.githubusercontent.com/12285528/130586128-a3b2a1c2-4a28-4d35-9de7-fb769712dd6e.png)


***While pyright server installed with this plugin works nicely***

![image](https://user-images.githubusercontent.com/12285528/130607193-b5009f3a-5f0d-44bc-89f7-f10f77b93ecd.png)

**Comment by nazo6** [comment]
I fixed angularls. Please update.

But I don't know why the html server doesn't work.
Do you get an error when you run `checkhealth lspconfig`?

**Comment by barungh** [comment]
> I fixed angularls. Please update.
> 
> But I don't know why the html server doesn't work.
> Do you get an error when you run `checkhealth lspconfig`?

During installation of Angularls , I noticed it was giving warning for node version

I downgraded node version 16xx (latest) to 14.xx.xx 
then it installed correctly and working fine 👍
