### ISSUE TITLE
Add emmet

### ISSUE THREAD

**Issue by nazo6** [nazo6/lspinstall.nvim#10]
@barungh It seems like emmet doesn't have cli. What kind of use do you envision for it? If you just want to use emmet with nvim, I think you should use something like [emmet-vim](https://github.com/mattn/emmet-vim).

**Comment by barungh** [comment]
I can use it , but I want to use something like it [this](https://github.com/aca/emmet-ls)

and I think , it is not installing properly in Windows host
I can use [coc emmet](https://github.com/neoclide/coc-emmet) too

**Comment by nazo6** [comment]
Does this mean that I should add emmet-ls?

**Comment by nazo6** [comment]
I added it for now. Is this fine?

**Comment by barungh** [comment]
I will check that , and update you

Thank You @nazo6 🤟🏻
