### ISSUE TITLE
All language server stopped working after latest upgrade

### ISSUE THREAD

**Issue by barungh** [nazo6/lspinstall.nvim#11]
All my language server are gone ( not detected ) after I updated the plugin address to ***nazo6/installer.nvim***

How can I revert back earlier version of the plugin ???

all my workflow is disturbed 😢 

I guess , changing the name caused some issue with ***lspconfig***

**Comment by nazo6** [comment]
Do you want to go back to v1? Then, you can use `main` branch to use old version.

```lua
use {
  'nazo6/lspinstall.nvim', branch = 'main'
}
```

**Comment by barungh** [comment]
Thank god , it is working again 🙇🏻‍♂️

**Comment by nazo6** [comment]
I should have written about incompatibilities. Sorry about that.
However, `main` branch will not be updated anymore, so if you can afford it, I recommend migrating to the v2 branch.

**Comment by barungh** [comment]
> I should have written about incompatibilities. Sorry about that.
> However, `main` branch will not be updated anymore, so if you can afford it, I recommend migrating to the v2 branch.

I will do that, I think i will need to integrate it with lspconfig manually, hence it is gonna take some time , for the time being i will be using the older version, till I finish the current project.

Thank you

**Comment by nazo6** [comment]
Of course, `main` branch still can be used, so there's no need to rush.
Thanks for using this plugin! 😄

**Comment by barungh** [comment]
Thanks

your plugin is life savior for me

sooner or later it's gonna catch the eyes of the users I believe
