### ISSUE TITLE
Which to use?

### ISSUE THREAD

**Issue by Borwe** [nazo6/lspinstall.nvim#12]
Is it recommended to use ```main``` or ```v2``` branch?
Also when contributing should people contribute to ```main``` or ```v2``` branch?

**Comment by nazo6** [comment]
Please use `v2` branch. I'm not going to update the `main` branch.
And also contribute to the v2 branch is recommended.

**Comment by Borwe** [comment]
> 
> 
> Please use `v2` branch. I'm not going to update the `main` branch.
> And also contribute to the v2 branch is recommended.

So ```main``` branch is dead?

**Comment by nazo6** [comment]
I'm not going to delete it, but yes, it is dead.

**Comment by Borwe** [comment]
Ooh, okay.
