### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by barungh** [nazo6/lspinstall.nvim#15]
This is my configuration ( please see left side ) 

at first it worked , but then stopped working 

![image](https://user-images.githubusercontent.com/12285528/137060943-bfcb14d9-3152-4c61-8c3f-ffbefdf0c793.png)

this is configuration file / module

![image](https://user-images.githubusercontent.com/12285528/137061192-f13d986b-f41c-4417-8406-9f92712d42be.png)

**Comment by nazo6** [comment]
I think your config is correct.
What is the meaning of "stopped working"?
Is server attached?

**Comment by barungh** [comment]
> I think your config is correct. What is the meaning of "stopped working"? Is server attached?

Yes servers are not attaching
I want to use your plugin with [Nvhcad's Neovim Configurations](https://github.com/NvChad/NvChad)
Earlier it was working, 
but after recent update on both , your plugin and Nvchad, 
servers are being installed with your plugin but not attached and does not work

after searching I found , Nvchad has provided a minimal configuration with `williamboman/nvim-lsp-installer`
I am providing a screenshot
Can you suggest me something with your plugin ? 
I want to use your plugin, because few features are available with your plugin only 
Thank You

![image](https://user-images.githubusercontent.com/12285528/137129922-b63e71e5-3dab-4bbb-a599-8d9f3a1423a0.png)

**Comment by nazo6** [comment]
I'm no longer updating the `main` branch so it should not be this plugin's problem.
But if you didn't update plugin for a long time, it may be this plugin's problem. If so, please tell me the commit that work correctly.
BTW, what is the feature that is not available in `nvim-lsp-installer`?

**Comment by barungh** [comment]
I will not use main branch, I will use default / current ( I think it is dev ) branch

with `nvim-lsp-installer` one thing which I am missing and need desperately is *Powershell lsp*

**Comment by nazo6** [comment]
According to your screenshot you seem to be using the `main` branch, but if you are using the` v2` branch you will need to rewrite the config according to the README.

**Comment by barungh** [comment]
![Screenshot 2021-10-13 182922](https://user-images.githubusercontent.com/12285528/137137426-230cd0ab-a414-470e-afff-3027a6156677.png)

![Screenshot 2021-10-13 182732](https://user-images.githubusercontent.com/12285528/137137447-e4ceec68-22ca-4049-8c23-96fe3aa19328.png)

![Screenshot 2021-10-13 182854](https://user-images.githubusercontent.com/12285528/137137468-d07f9a26-65fe-4289-ad96-aa72087b34e3.png)

what am I missing ?

**Comment by nazo6** [comment]
Did you add this
```lua
require("installer.integrations.ls").setup {
  enable_hook = true
}
```
to config?
And you have to reload buffer after install.

**Comment by barungh** [comment]
Yes , and this is what I get after this

![image](https://user-images.githubusercontent.com/12285528/137140064-49b96424-fe54-437b-9975-02d24c687196.png)

**Comment by nazo6** [comment]
Hm, you installed `nvim-lspconfig`, didn't you? then, it is weird.

Anyway, try this
```lua
use { "nazo6/installer.nvim",
  requires = {"nvim-lua/plenary.nvim", "neovim/nvim-lspconfig"}
}
```

**Comment by barungh** [comment]
Now getting this
![image](https://user-images.githubusercontent.com/12285528/137142127-0ccd2d0e-a85c-4864-a20e-d389e6e2cbd2.png)

**Comment by nazo6** [comment]
Please post full `nazolsp.lua`

**Comment by barungh** [comment]
![image](https://user-images.githubusercontent.com/12285528/137143010-8748fd53-237d-45c1-a90b-9a51bba113fc.png)
Here it is

**Comment by barungh** [comment]
Wait 
Now I am getting this

![image](https://user-images.githubusercontent.com/12285528/137143358-3030b9b9-2ffb-4d15-8a7e-18b87b3ef533.png)


Servers are installed, executable found, but not attaching

**Comment by nazo6** [comment]
I think it will take some time for powershell_es to be attached
If it still doesn't work, please check lsp.log
