### ISSUE TITLE
Using nvim/lspconfig that don't have a setup option

### ISSUE THREAD

**Issue by Borwe** [nazo6/lspinstall.nvim#16]
How to use nvim/lspconfig for language servers that don't produce directories, eg: rls language server since only way known to get it is through cargo which is another application by itself.

**Comment by nazo6** [comment]
I’m sorry but I can't understand what you say. Would you be able to explain a little more?

**Comment by Borwe** [comment]
For example an lsp server that has configs in nvim/lspconfig, but no install step for it exists, i.e: User has to manually install the server. How would I be able to use it with this one?

**Comment by nazo6** [comment]
I think just using nvim-lspconfig's setup function directly is ok.

**Comment by Borwe** [comment]
LOL, been using this for so long, forgot such a thing existed. Thanks.
