### ISSUE TITLE
Sumenko Lua lsp not installing

### ISSUE THREAD

**Issue by barungh** [nazo6/lspinstall.nvim#2]
![image](https://user-images.githubusercontent.com/12285528/130591841-d5fde7d7-6220-49df-a6e3-1043ac73dafd.png)

***After launch of IE***

![image](https://user-images.githubusercontent.com/12285528/130592270-b1e9618f-6490-43d0-a270-e2d3d76eaa66.png)

**Tried Importing Module**

![image](https://user-images.githubusercontent.com/12285528/130592685-a56cbae5-a2f5-4810-ad06-9c1350adf1f0.png)

**Comment by nazo6** [comment]
Now that I have added the "-UseBasicParsing" option, so "Invoke-WebRequest" should work fine.

But I'm not sure about the latter issue. Are you using Windows 10?

**Comment by nazo6** [comment]
Now that I have added the "-UseBasicParsing" option, so "Invoke-WebRequest" should work fine without IE.

But I'm not sure about the latter issue...

**Comment by barungh** [comment]
updated the plugin 
![image](https://user-images.githubusercontent.com/12285528/130636230-fafd1fbb-d906-4a3b-a2ae-2a8a58b02c42.png)

then getting this error 

![image](https://user-images.githubusercontent.com/12285528/130636383-7dc90c54-9af6-484d-9f51-93f00c1e4c42.png)

I am on Windows 10 powershell 7.1.4

![image](https://user-images.githubusercontent.com/12285528/130637550-09da39c2-76ce-4d5e-b24a-269b97680d9b.png)

**Comment by barungh** [comment]
![image](https://user-images.githubusercontent.com/12285528/130638083-abde7e3f-33d4-464c-9928-8dd3beebe745.png)

I tried with elevated ps also 

but I think finally it is working with ***Powershell 5 only*** 

I will confirm, lemme test it

**Comment by barungh** [comment]
Yes ,

`:LspInstall sumenko_lua` did not work on Powershell 7.1.4 (latest)

but it does work on Powershell 5 (without admin priviledge)
and once it is installed , Lsp works in Powershell 7 also

![image](https://user-images.githubusercontent.com/12285528/130638973-4db3ff3f-3a63-45bd-9804-b47366771255.png)

**Comment by barungh** [comment]
I think you should provide info about these compatibility issue in your Readme or wiki 
or
if possible, fix these issues

since my problems are solved , I am closing this issue,

thanks 👍

**Comment by nazo6** [comment]
How did you solve this problem?
I think it should always open powershell 5, because I specified `powershell.exe` as the shell when install. Since powershell 6, its excutable is `pwsh.exe`.

**Comment by barungh** [comment]
> How did you solve this problem?
> I think it should always open powershell 5, because I specified `powershell.exe` as the shell when install. Since powershell 6, its excutable is `pwsh.exe`.

I use Windows Terminal ,

where default shell is Powershell 7
![image](https://user-images.githubusercontent.com/12285528/130641295-43aac8c4-2d10-4adb-9260-e79613866af7.png)

I noticed some modules were present but was not being imported

so first i tried with elevated powershell, but did not work

then i opened powershell 5, and run `nvim` and did `:LspInstall sumenko_lua` and it worked

**Comment by nazo6** [comment]
Thanks. I understood.
However, I'm also running nvim on Powershell 7 and I'm not having this problem. Anyway, until I find a solution, I'll put it in the README.
