### ISSUE TITLE
Omnisharp C# server not working

### ISSUE THREAD

**Issue by barungh** [nazo6/lspinstall.nvim#6]
![image](https://user-images.githubusercontent.com/12285528/132077288-60f8f2b9-c182-44af-aa5b-1127a94de41f.png)

Can you fix this ?

After installing omnisharp language server I fell hook command to attach client is not being executed.

How do I solve this problem ? any suggestion ?

Thank You

**Comment by nazo6** [comment]
I'm not familiar with C#/.NET. Can you give me the procedure to reproduce it?

**Comment by barungh** [comment]
It should work in any `.cs` file

I will provide more details within few hours

**Comment by nazo6** [comment]
Thanks, but I could reproduce it. I'm looking for a solution.

**Comment by barungh** [comment]
> Thanks, but I could reproduce it. I'm looking for a solution.

Take any C sharp/ [dot net](https://dotnet.microsoft.com/) project / file, which has .cs extension

Open it in Nvim, install omnisharp server, :LspInstall omnisharp/csharp 

it should attach the client and provide the language features

Thanks

**Comment by barungh** [comment]
See, in my Linux machine, using [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall),
I installed `csharp` language server

![2021-09-04-213228_253x799_scrot](https://user-images.githubusercontent.com/12285528/132091670-15dba96c-e894-46fd-9b51-09848ed5a0e6.png)

Obviously it installed without any issue, 

![2021-09-04-212956_938x1033_scrot](https://user-images.githubusercontent.com/12285528/132091677-8711c879-29b8-4ae8-9802-233bc92250b5.png)

and instantly it was hooked and providing LSP features

![2021-09-04-213033_946x1042_scrot](https://user-images.githubusercontent.com/12285528/132091691-7b3ed9cf-3643-44ce-83cd-506d21f3d469.png)

![2021-09-04-213120_949x314_scrot](https://user-images.githubusercontent.com/12285528/132091693-3e7fb6f3-fbdc-4133-88a9-f08a985807f4.png)


with your plugin it is named as `Omnisharp`

It probably installs, but not working

Thank You

**Comment by nazo6** [comment]
I fixed the problem.
Please update plugin and execute `LspReInstall omnisharp`.

**Comment by barungh** [comment]
> I fixed the problem.
> Please update plugin and execute `LspReInstall omnisharp`.

Yes it worked in my Windows 10 machine

![Screenshot 2021-09-04 173552](https://user-images.githubusercontent.com/12285528/132093955-299c8cc1-cbbf-4dc7-8c6e-75510312c8b2.png)

great ! 👍🏻 

![image](https://user-images.githubusercontent.com/12285528/132093958-f2a8f580-95fd-463d-b881-5bd98cec0529.png)

Awesome ! you are a true Japanese 🥰 

Thank You so much
